spring:
  application:
    name: gw
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        #加载所有的端点，默认只加载了info、health
        include: '*'
  endpoint:
    health:
      show-details: always
    #可以关闭指定的端点
    shutdown:
      enabled: false

multiple:
  frame:
    default-keys: signCheck
    interceptor-keys:
        dc: methodMappingUri

  sign:
    skip-check: true
  parser:
    cache-start: true
    template-suffix: '.json'
    template-path: 'template/%s/biz/%s'
  plugin:
    load:
     - name: unCompress
       order: 1111
























