spring:
  application:
    name: gw
server:
  port: 8080
  servlet:
    context-path: /gw


multiple:
  frame:
    interceptor-keys:
      dc: methodMappingUri
  sign:
    skip-check: true
  parser:
    cache-start: true
    template-suffix: '.json'
    template-path: 'template/%s/biz/%s'
  plugin:
    load:
     - name: unCompress
       order: 1111


management:
  endpoints:
    web:
      exposure:
        include: heapdump,liquibase,loggers,prometheus,threaddump,info,metrics,health

















