spring:
  application:
    name: gw
server:
  port: 8080
multiple:
  sign:
    skip-check: true
  parser:
    cache-start: true
    template-suffix: '.json'
    template-path: 'template/%s/biz/%s'








